import { useState, useEffect } from "react";

export type Lang = "ar" | "en" | "fr";

const KEY = "robotech_lang";

export const translations = {
  ar: {
    dir: "rtl",
    // Header
    home: "الرئيسية",
    labs: "المختبرات",
    howWork: "كيف نعمل؟",
    light: "فاتح",
    dark: "داكن",
    logout: "تسجيل الخروج",
    // Hero
    heroBadge: "أكاديمية RoboTech — منصة تعليم الروبوتيك للأطفال",
    heroTitle1: "أهلاً بك",
    heroTitle2: "استعد لمغامرة الروبوتيك 🚀",
    heroSub: "اكتشف عالم الروبوتات والبرمجة عبر مختبرات تفاعلية مدهشة، فيديوهات احترافية، ومحاكيات متطورة. كل هذا مجاناً وباللغة العربية.",
    startExplore: "ابدأ الاستكشاف",
    howItWork: "كيف يعمل؟",
    // Stats
    stat1: "مختبراً تفاعلياً",
    stat2: "درساً بالفيديو",
    stat3: "تحدياً للأبطال",
    stat4: "مغامرة تنتظرك",
    // Labs section
    chooseLab: "اختر مختبرك",
    labsDesc: "كل مختبر يحتوي على فيديوهات شرح + محاكي تفاعلي + قائمة مهام البطل",
    filterAll: "🌟 الكل",
    filterBeg: "🟢 مبتدئ",
    filterInt: "🟡 متوسط",
    filterAdv: "🔴 متقدم",
    enterLab: "ادخل المختبر",
    lessons: "دروس",
    yearsOld: "سنة",
    // How section
    howTitle: "كيف تبدأ؟",
    how1Title: "اختر مختبرك",
    how1Desc: "انقر على أي مختبر من الشبكة أدناه",
    how2Title: "شاهد الشرح",
    how2Desc: "فيديوهات قصيرة وممتعة تشرح كل خطوة",
    how3Title: "جرّب المحاكي",
    how3Desc: "طبّق مباشرةً في المحاكي التفاعلي",
    how4Title: "أنجز المهام",
    how4Desc: "اكمل قائمة البطل واحصد إنجازاتك",
    // Login
    loginWelcomeBack: "أهلاً بعودتك يا بطل! 🌟",
    loginJoin: "انضم إلى عالم الروبوتيك! 🚀",
    loginTab: "تسجيل الدخول",
    signupTab: "حساب جديد",
    nameLabel: "اسمك (ماذا نناديك؟)",
    namePlaceholder: "مثال: محمد البطل",
    emailLabel: "البريد الإلكتروني",
    passLabel: "كلمة المرور",
    passPlaceholder6: "6 أحرف على الأقل",
    loginBtn: "ابدأ المغامرة!",
    signupBtn: "أنشئ حسابي!",
    checking: "جاري التحقق...",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    signupFree: "سجّل مجاناً",
    doLogin: "سجّل دخولك",
    demoHint: "جرب: أي بريد + أي كلمة مرور (6 أحرف) للتسجيل السريع",
    // Lab view
    backHome: "الرئيسية",
    reload: "إعادة تحميل",
    openSep: "فتح منفصلاً",
    yourProgress: "تقدمك في المختبر",
    lessonsList: "قائمة الدروس",
    heroTasks: "مهام البطل",
    acquiredSkills: "المهارات المكتسبة",
    launchSim: "تشغيل المحاكي",
    openNew: "فتح في نافذة جديدة (أسرع)",
    clickToLoad: "انقر على الزر أدناه لتحميل المحاكي التفاعلي",
    loading: "جاري تحميل",
    loadHint: "قد يستغرق بعض الوقت — يُحمَّل مرة واحدة فقط",
    lessonsCount: "دروس",
    footer: "© 2026 أكاديمية RoboTech — جميع الحقوق محفوظة",
    footerContact: "تواصل معنا",
    footerFollow: "تابعنا",
    langLabel: "اللغة",
    dashboard: "تقدمي",
    toastAllDone: "أنجزت جميع مهام البطل! أنت خارق 🎉",
    toastTaskDone: "تم إنجاز المهمة",
    badgeNew: "إنجاز جديد!",
    videoErrorTitle: "الفيديو لم يُحمَّل",
    videoErrorPrefix: "خطأ",
    videoOpenNewTab: "افتح الفيديو في تبويب جديد ↗",
    quizStart: "ابدأ الاختبار",
    quizPassed: "تم اجتيازه ✓",
    quizQuestion: "سؤال",
    quizNext: "التالي",
    quizShowResult: "إظهار النتيجة",
    quizPassedTitle: "أحسنت! 🎉",
    quizFailedTitle: "حاول مرة أخرى",
    quizPassedMsg: "اجتزت الاختبار بنجاح، الدرس الآن مكتمل.",
    quizFailedMsg: "تحتاج {p}% أو أكثر للنجاح. شاهد الفيديو مجدداً وحاول.",
    quizContinue: "متابعة",
    quizRetry: "إعادة الاختبار",
    quizClose: "إغلاق",
    quizNoQuiz: "لا يوجد اختبار لهذا الدرس",
    quizMarkWatched: "تم تأكيد المشاهدة",
    certUnlocked: "شهادة الإنجاز جاهزة!",
    certUnlockHint: "أكملت كل الدروس والمهام — احصل على شهادتك الآن.",
    certShow: "عرض الشهادة",
    certDownload: "تنزيل PDF",
    certPreparing: "جاري التحضير...",
    certError: "تعذّر إنشاء ملف PDF، حاول مرة أخرى.",
    certTitle: "شهادة إنجاز",
    certBrandSub: "منصة تعليم الروبوتيك",
    certHeadline: "شهادة إتمام",
    certPresentedTo: "تُمنح هذه الشهادة بكل فخر إلى",
    certForCompleting: "تقديراً لإتمام جميع دروس ومهام مختبر",
    certDate: "التاريخ",
    certId: "رقم الشهادة",
    certLockedHint: "أكمل جميع الدروس والمهام لفتح الشهادة",
    pwaInstallTitle: "ثبّت RoboTech على جهازك!",
    pwaInstallHint: "افتحه كتطبيق، يعمل دون إنترنت.",
    pwaIOSHint: "اضغط على مشاركة ⇧ ثم \"إضافة إلى الشاشة الرئيسية\".",
    pwaInstallBtn: "تثبيت",
    pwaDismiss: "إغلاق",
    pwaEnableNotifs: "فعّل التذكيرات اليومية",
    pwaNotifsOn: "التذكيرات مفعّلة 🔔",
    pwaNotifsBlocked: "التذكيرات محظورة من المتصفّح",
    reminderTitle: "🤖 وقت التعلّم في RoboTech!",
    reminderBody: "درسٌ جديد ينتظرك اليوم. هيا نكمل المغامرة!",
    reminderBodyNamed: "مرحباً {name}! درسٌ جديد ينتظرك. هيا نكمل المغامرة!",
    xpLevel: "المستوى",
    xpLevelUp: "🎉 ارتقيت للمستوى {n}!",
    xpKeepGoing: "تابع التعلّم لتصبح أسطورة!",
    xpEarned: "نقطة خبرة",
    xpBadgeNew: "شارة جديدة!",
    xpStreak: "أيام متواصلة:",
    xpLeaderboard: "لوحة المتصدّرين",
    xpLeaderboardSub: "تنافس مع باقي المتعلّمين واجمع شارات الإنجاز!",
    xpRanking: "الترتيب",
    xpMyBadges: "شاراتي",
    xpLocked: "شارات لم تُفتح بعد",
    xpNoOthers: "كن أوّل المتصدّرين!",
    xpYou: "أنت",
  },
  en: {
    dir: "ltr",
    home: "Home",
    labs: "Labs",
    howWork: "How it works?",
    light: "Light",
    dark: "Dark",
    logout: "Logout",
    heroBadge: "RoboTech Academy — Robotics Education for Kids",
    heroTitle1: "Welcome",
    heroTitle2: "Get ready for adventure 🚀",
    heroSub: "Discover the world of robotics and programming through amazing interactive labs, professional videos, and advanced simulators. All for free.",
    startExplore: "Start Exploring",
    howItWork: "How it works?",
    stat1: "Interactive Labs",
    stat2: "Video Lessons",
    stat3: "Hero Challenges",
    stat4: "Adventures Await",
    chooseLab: "Choose Your Lab",
    labsDesc: "Each lab includes explanation videos + interactive simulator + hero task list",
    filterAll: "🌟 All",
    filterBeg: "🟢 Beginner",
    filterInt: "🟡 Intermediate",
    filterAdv: "🔴 Advanced",
    enterLab: "Enter Lab",
    lessons: "lessons",
    yearsOld: "yrs",
    howTitle: "How to Start?",
    how1Title: "Choose Your Lab",
    how1Desc: "Click on any lab from the grid below",
    how2Title: "Watch Explanation",
    how2Desc: "Short and fun videos explaining every step",
    how3Title: "Try the Simulator",
    how3Desc: "Practice directly in the interactive simulator",
    how4Title: "Complete Tasks",
    how4Desc: "Finish the hero list and collect your achievements",
    loginWelcomeBack: "Welcome back, champion! 🌟",
    loginJoin: "Join the world of robotics! 🚀",
    loginTab: "Login",
    signupTab: "New Account",
    nameLabel: "Your Name",
    namePlaceholder: "e.g. Ahmed the Hero",
    emailLabel: "Email Address",
    passLabel: "Password",
    passPlaceholder6: "At least 6 characters",
    loginBtn: "Start Adventure!",
    signupBtn: "Create My Account!",
    checking: "Verifying...",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signupFree: "Sign up free",
    doLogin: "Log in",
    demoHint: "Try: any email + any password (6 chars) for quick signup",
    backHome: "Home",
    reload: "Reload",
    openSep: "Open Separately",
    yourProgress: "Your Progress",
    lessonsList: "Lessons List",
    heroTasks: "Hero Tasks",
    acquiredSkills: "Acquired Skills",
    launchSim: "Launch Simulator",
    openNew: "Open in New Window (Faster)",
    clickToLoad: "Click the button below to load the interactive simulator",
    loading: "Loading",
    loadHint: "This may take a moment — loaded only once",
    lessonsCount: "lessons",
    footer: "© 2026 RoboTech Academy — All rights reserved",
    footerContact: "Contact us",
    footerFollow: "Follow us",
    langLabel: "Language",
    dashboard: "My Progress",
    toastAllDone: "You finished all hero tasks. You're amazing 🎉",
    toastTaskDone: "Task completed:",
    badgeNew: "New Achievement!",
    videoErrorTitle: "Video failed to load",
    videoErrorPrefix: "Error",
    videoOpenNewTab: "Open video in new tab ↗",
    quizStart: "Start Quiz",
    quizPassed: "Passed ✓",
    quizQuestion: "Question",
    quizNext: "Next",
    quizShowResult: "Show Result",
    quizPassedTitle: "Well Done! 🎉",
    quizFailedTitle: "Try Again",
    quizPassedMsg: "You passed the quiz — the lesson is now complete.",
    quizFailedMsg: "You need {p}% or more to pass. Watch the video again and try.",
    quizContinue: "Continue",
    quizRetry: "Retry Quiz",
    quizClose: "Close",
    quizNoQuiz: "No quiz available for this lesson",
    quizMarkWatched: "Mark as watched",
    certUnlocked: "Your Certificate is Ready!",
    certUnlockHint: "You finished every lesson and task — claim your certificate now.",
    certShow: "View Certificate",
    certDownload: "Download PDF",
    certPreparing: "Preparing...",
    certError: "Could not create PDF. Please try again.",
    certTitle: "Certificate of Completion",
    certBrandSub: "Robotics Education Platform",
    certHeadline: "Certificate of Completion",
    certPresentedTo: "This certificate is proudly presented to",
    certForCompleting: "For successfully completing all lessons and tasks of",
    certDate: "Date",
    certId: "Certificate ID",
    certLockedHint: "Complete all lessons and tasks to unlock the certificate",
    pwaInstallTitle: "Install RoboTech on your device!",
    pwaInstallHint: "Open it as an app — works offline.",
    pwaIOSHint: "Tap Share ⇧ then \"Add to Home Screen\".",
    pwaInstallBtn: "Install",
    pwaDismiss: "Close",
    pwaEnableNotifs: "Enable daily reminders",
    pwaNotifsOn: "Reminders enabled 🔔",
    pwaNotifsBlocked: "Notifications blocked in browser",
    reminderTitle: "🤖 Time to learn at RoboTech!",
    reminderBody: "A new lesson is waiting today. Let's continue the adventure!",
    reminderBodyNamed: "Hi {name}! A new lesson is waiting. Let's continue the adventure!",
    xpLevel: "Level",
    xpLevelUp: "🎉 Leveled up to {n}!",
    xpKeepGoing: "Keep learning to become a legend!",
    xpEarned: "XP earned",
    xpBadgeNew: "New badge!",
    xpStreak: "Day streak:",
    xpLeaderboard: "Leaderboard",
    xpLeaderboardSub: "Compete with other learners and collect badges!",
    xpRanking: "Ranking",
    xpMyBadges: "My Badges",
    xpLocked: "Locked badges",
    xpNoOthers: "Be the first on the leaderboard!",
    xpYou: "You",
  },
  fr: {
    dir: "ltr",
    home: "Accueil",
    labs: "Laboratoires",
    howWork: "Comment ça marche?",
    light: "Clair",
    dark: "Sombre",
    logout: "Déconnexion",
    heroBadge: "Académie RoboTech — Éducation Robotique pour Enfants",
    heroTitle1: "Bienvenue",
    heroTitle2: "Prêt pour l'aventure 🚀",
    heroSub: "Découvrez le monde de la robotique et de la programmation à travers des laboratoires interactifs, des vidéos professionnelles et des simulateurs avancés. Tout est gratuit.",
    startExplore: "Commencer l'exploration",
    howItWork: "Comment ça marche?",
    stat1: "Labos Interactifs",
    stat2: "Leçons Vidéo",
    stat3: "Défis Héros",
    stat4: "Aventures t'attendent",
    chooseLab: "Choisissez votre Labo",
    labsDesc: "Chaque labo comprend des vidéos + un simulateur interactif + une liste de tâches héros",
    filterAll: "🌟 Tous",
    filterBeg: "🟢 Débutant",
    filterInt: "🟡 Intermédiaire",
    filterAdv: "🔴 Avancé",
    enterLab: "Entrer dans le Labo",
    lessons: "leçons",
    yearsOld: "ans",
    howTitle: "Comment commencer?",
    how1Title: "Choisissez votre Labo",
    how1Desc: "Cliquez sur n'importe quel labo dans la grille",
    how2Title: "Regardez l'explication",
    how2Desc: "Des vidéos courtes et amusantes qui expliquent chaque étape",
    how3Title: "Essayez le simulateur",
    how3Desc: "Pratiquez directement dans le simulateur interactif",
    how4Title: "Complétez les tâches",
    how4Desc: "Terminez la liste héros et récoltez vos réalisations",
    loginWelcomeBack: "Bienvenue, champion! 🌟",
    loginJoin: "Rejoignez le monde de la robotique! 🚀",
    loginTab: "Connexion",
    signupTab: "Nouveau Compte",
    nameLabel: "Votre Prénom",
    namePlaceholder: "ex. Ahmed le Héros",
    emailLabel: "Adresse Email",
    passLabel: "Mot de Passe",
    passPlaceholder6: "Au moins 6 caractères",
    loginBtn: "Commencer l'Aventure!",
    signupBtn: "Créer Mon Compte!",
    checking: "Vérification...",
    noAccount: "Pas de compte?",
    hasAccount: "Déjà un compte?",
    signupFree: "S'inscrire gratuitement",
    doLogin: "Se connecter",
    demoHint: "Essayez: n'importe quel email + mot de passe (6 chars) pour inscription rapide",
    backHome: "Accueil",
    reload: "Recharger",
    openSep: "Ouvrir séparément",
    yourProgress: "Votre Progression",
    lessonsList: "Liste des Leçons",
    heroTasks: "Tâches Héros",
    acquiredSkills: "Compétences Acquises",
    launchSim: "Lancer le Simulateur",
    openNew: "Ouvrir dans Nouvelle Fenêtre (Plus rapide)",
    clickToLoad: "Cliquez sur le bouton ci-dessous pour charger le simulateur",
    loading: "Chargement de",
    loadHint: "Cela peut prendre un moment — chargé une seule fois",
    lessonsCount: "leçons",
    footer: "© 2026 Académie RoboTech — Tous droits réservés",
    footerContact: "Contactez-nous",
    footerFollow: "Suivez-nous",
    langLabel: "Langue",
    dashboard: "Ma Progression",
    toastAllDone: "Vous avez terminé toutes les tâches héros 🎉",
    toastTaskDone: "Tâche terminée:",
    badgeNew: "Nouvelle réalisation !",
    videoErrorTitle: "Échec du chargement de la vidéo",
    videoErrorPrefix: "Erreur",
    videoOpenNewTab: "Ouvrir la vidéo dans un nouvel onglet ↗",
    quizStart: "Démarrer le Quiz",
    quizPassed: "Réussi ✓",
    quizQuestion: "Question",
    quizNext: "Suivant",
    quizShowResult: "Voir le Résultat",
    quizPassedTitle: "Bravo ! 🎉",
    quizFailedTitle: "Réessayer",
    quizPassedMsg: "Quiz réussi — la leçon est maintenant terminée.",
    quizFailedMsg: "Il faut {p}% ou plus pour réussir. Revoyez la vidéo et réessayez.",
    quizContinue: "Continuer",
    quizRetry: "Recommencer",
    quizClose: "Fermer",
    quizNoQuiz: "Pas de quiz pour cette leçon",
    quizMarkWatched: "Marquer comme vu",
    certUnlocked: "Votre certificat est prêt !",
    certUnlockHint: "Vous avez terminé toutes les leçons et tâches — obtenez votre certificat.",
    certShow: "Voir le certificat",
    certDownload: "Télécharger PDF",
    certPreparing: "Préparation...",
    certError: "Impossible de créer le PDF. Réessayez.",
    certTitle: "Certificat de Réussite",
    certBrandSub: "Plateforme d'Éducation Robotique",
    certHeadline: "Certificat de Réussite",
    certPresentedTo: "Ce certificat est fièrement décerné à",
    certForCompleting: "Pour avoir complété avec succès toutes les leçons et tâches de",
    certDate: "Date",
    certId: "ID du Certificat",
    certLockedHint: "Terminez toutes les leçons et tâches pour débloquer le certificat",
    pwaInstallTitle: "Installez RoboTech sur votre appareil !",
    pwaInstallHint: "Ouvrez-le comme une appli — fonctionne hors-ligne.",
    pwaIOSHint: "Appuyez sur Partager ⇧ puis \"Sur l'écran d'accueil\".",
    pwaInstallBtn: "Installer",
    pwaDismiss: "Fermer",
    pwaEnableNotifs: "Activer les rappels quotidiens",
    pwaNotifsOn: "Rappels activés 🔔",
    pwaNotifsBlocked: "Notifications bloquées par le navigateur",
    reminderTitle: "🤖 C'est l'heure d'apprendre sur RoboTech !",
    reminderBody: "Une nouvelle leçon vous attend. Continuons l'aventure !",
    reminderBodyNamed: "Salut {name} ! Une nouvelle leçon vous attend. Continuons l'aventure !",
    xpLevel: "Niveau",
    xpLevelUp: "🎉 Niveau {n} atteint !",
    xpKeepGoing: "Continuez pour devenir une légende !",
    xpEarned: "XP gagnés",
    xpBadgeNew: "Nouveau badge !",
    xpStreak: "Jours d'affilée :",
    xpLeaderboard: "Classement",
    xpLeaderboardSub: "Affrontez les autres et collectez des badges !",
    xpRanking: "Classement",
    xpMyBadges: "Mes Badges",
    xpLocked: "Badges verrouillés",
    xpNoOthers: "Soyez le premier au classement !",
    xpYou: "Vous",
  },
} as const;

export type T = typeof translations.ar & { dir: "rtl" | "ltr" };

export function useLang() {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem(KEY) as Lang) ?? "ar";
  });

  useEffect(() => {
    localStorage.setItem(KEY, lang);
    const t = translations[lang];
    document.documentElement.setAttribute("dir", t.dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang]);

  const t = translations[lang] as unknown as T;

  return { lang, setLang, t };
}
