import { useState, useEffect } from "react";

export type Lang = "ar" | "en" | "fr";

const KEY = "robotech_lang";

export const translations = {
  ar: {
    dir: "rtl",
    // Header
    home: "الرئيسية",
    labs: "المختبرات",
    howWork: "كيف نعمل؟",
    light: "فاتح",
    dark: "داكن",
    logout: "تسجيل الخروج",
    // Hero
    heroBadge: "أكاديمية RoboTech — منصة تعليم الروبوتيك للأطفال",
    heroTitle1: "أهلاً",
    heroTitle2: "استعد للمغامرة 🚀",
    heroSub: "اكتشف عالم الروبوتات والبرمجة عبر مختبرات تفاعلية مدهشة، فيديوهات احترافية، ومحاكيات متطورة — كل هذا مجاناً وباللغة العربية.",
    startExplore: "ابدأ الاستكشاف",
    howItWork: "كيف يعمل؟",
    // Stats
    stat1: "مختبراً تفاعلياً",
    stat2: "درساً بالفيديو",
    stat3: "تحدياً للأبطال",
    stat4: "مغامرة تنتظرك",
    // Labs section
    chooseLab: "اختر مختبرك",
    labsDesc: "كل مختبر يحتوي على فيديوهات شرح + محاكي تفاعلي + قائمة مهام البطل",
    filterAll: "🌟 الكل",
    filterBeg: "🟢 مبتدئ",
    filterInt: "🟡 متوسط",
    filterAdv: "🔴 متقدم",
    enterLab: "ادخل المختبر",
    lessons: "دروس",
    yearsOld: "سنة",
    // How section
    howTitle: "كيف تبدأ؟",
    how1Title: "اختر مختبرك",
    how1Desc: "انقر على أي مختبر من الشبكة أدناه",
    how2Title: "شاهد الشرح",
    how2Desc: "فيديوهات قصيرة وممتعة تشرح كل خطوة",
    how3Title: "جرّب المحاكي",
    how3Desc: "طبّق مباشرةً في المحاكي التفاعلي",
    how4Title: "أنجز المهام",
    how4Desc: "اكمل قائمة البطل واحصد إنجازاتك",
    // Login
    loginWelcomeBack: "أهلاً بعودتك يا بطل! 🌟",
    loginJoin: "انضم إلى عالم الروبوتيك! 🚀",
    loginTab: "تسجيل الدخول",
    signupTab: "حساب جديد",
    nameLabel: "اسمك (ماذا نناديك؟)",
    namePlaceholder: "مثال: محمد البطل",
    emailLabel: "البريد الإلكتروني",
    passLabel: "كلمة المرور",
    passPlaceholder6: "6 أحرف على الأقل",
    loginBtn: "ابدأ المغامرة!",
    signupBtn: "أنشئ حسابي!",
    checking: "جاري التحقق...",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    signupFree: "سجّل مجاناً",
    doLogin: "سجّل دخولك",
    demoHint: "جرب: أي بريد + أي كلمة مرور (6 أحرف) للتسجيل السريع",
    // Lab view
    backHome: "الرئيسية",
    reload: "إعادة تحميل",
    openSep: "فتح منفصلاً",
    yourProgress: "تقدمك في المختبر",
    lessonsList: "قائمة الدروس",
    heroTasks: "مهام البطل",
    acquiredSkills: "المهارات المكتسبة",
    launchSim: "تشغيل المحاكي",
    openNew: "فتح في نافذة جديدة (أسرع)",
    clickToLoad: "انقر على الزر أدناه لتحميل المحاكي التفاعلي",
    loading: "جاري تحميل",
    loadHint: "قد يستغرق بعض الوقت — يُحمَّل مرة واحدة فقط",
    lessonsCount: "دروس",
    footer: "© 2025 أكاديمية RoboTech — تعليم الروبوتيك للجيل القادم بطريقة ممتعة وآمنة",
    langLabel: "اللغة",
    dashboard: "تقدمي",
  },
  en: {
    dir: "ltr",
    home: "Home",
    labs: "Labs",
    howWork: "How it works?",
    light: "Light",
    dark: "Dark",
    logout: "Logout",
    heroBadge: "RoboTech Academy — Robotics Education for Kids",
    heroTitle1: "Hello",
    heroTitle2: "Get ready for adventure 🚀",
    heroSub: "Discover the world of robotics and programming through amazing interactive labs, professional videos, and advanced simulators — all for free!",
    startExplore: "Start Exploring",
    howItWork: "How it works?",
    stat1: "Interactive Labs",
    stat2: "Video Lessons",
    stat3: "Hero Challenges",
    stat4: "Adventures Await",
    chooseLab: "Choose Your Lab",
    labsDesc: "Each lab includes explanation videos + interactive simulator + hero task list",
    filterAll: "🌟 All",
    filterBeg: "🟢 Beginner",
    filterInt: "🟡 Intermediate",
    filterAdv: "🔴 Advanced",
    enterLab: "Enter Lab",
    lessons: "lessons",
    yearsOld: "yrs",
    howTitle: "How to Start?",
    how1Title: "Choose Your Lab",
    how1Desc: "Click on any lab from the grid below",
    how2Title: "Watch Explanation",
    how2Desc: "Short and fun videos explaining every step",
    how3Title: "Try the Simulator",
    how3Desc: "Practice directly in the interactive simulator",
    how4Title: "Complete Tasks",
    how4Desc: "Finish the hero list and collect your achievements",
    loginWelcomeBack: "Welcome back, champion! 🌟",
    loginJoin: "Join the world of robotics! 🚀",
    loginTab: "Login",
    signupTab: "New Account",
    nameLabel: "Your Name",
    namePlaceholder: "e.g. Ahmed the Hero",
    emailLabel: "Email Address",
    passLabel: "Password",
    passPlaceholder6: "At least 6 characters",
    loginBtn: "Start Adventure!",
    signupBtn: "Create My Account!",
    checking: "Verifying...",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signupFree: "Sign up free",
    doLogin: "Log in",
    demoHint: "Try: any email + any password (6 chars) for quick signup",
    backHome: "Home",
    reload: "Reload",
    openSep: "Open Separately",
    yourProgress: "Your Progress",
    lessonsList: "Lessons List",
    heroTasks: "Hero Tasks",
    acquiredSkills: "Acquired Skills",
    launchSim: "Launch Simulator",
    openNew: "Open in New Window (Faster)",
    clickToLoad: "Click the button below to load the interactive simulator",
    loading: "Loading",
    loadHint: "This may take a moment — loaded only once",
    lessonsCount: "lessons",
    footer: "© 2025 RoboTech Academy — Robotics education for the next generation",
    langLabel: "Language",
    dashboard: "My Progress",
  },
  fr: {
    dir: "ltr",
    home: "Accueil",
    labs: "Laboratoires",
    howWork: "Comment ça marche?",
    light: "Clair",
    dark: "Sombre",
    logout: "Déconnexion",
    heroBadge: "Académie RoboTech — Éducation Robotique pour Enfants",
    heroTitle1: "Bonjour",
    heroTitle2: "Prêt pour l'aventure 🚀",
    heroSub: "Découvrez le monde de la robotique et de la programmation à travers des laboratoires interactifs, des vidéos professionnelles et des simulateurs avancés — tout gratuitement!",
    startExplore: "Commencer l'exploration",
    howItWork: "Comment ça marche?",
    stat1: "Labos Interactifs",
    stat2: "Leçons Vidéo",
    stat3: "Défis Héros",
    stat4: "Aventures t'attendent",
    chooseLab: "Choisissez votre Labo",
    labsDesc: "Chaque labo comprend des vidéos + un simulateur interactif + une liste de tâches héros",
    filterAll: "🌟 Tous",
    filterBeg: "🟢 Débutant",
    filterInt: "🟡 Intermédiaire",
    filterAdv: "🔴 Avancé",
    enterLab: "Entrer dans le Labo",
    lessons: "leçons",
    yearsOld: "ans",
    howTitle: "Comment commencer?",
    how1Title: "Choisissez votre Labo",
    how1Desc: "Cliquez sur n'importe quel labo dans la grille",
    how2Title: "Regardez l'explication",
    how2Desc: "Des vidéos courtes et amusantes qui expliquent chaque étape",
    how3Title: "Essayez le simulateur",
    how3Desc: "Pratiquez directement dans le simulateur interactif",
    how4Title: "Complétez les tâches",
    how4Desc: "Terminez la liste héros et récoltez vos réalisations",
    loginWelcomeBack: "Bienvenue, champion! 🌟",
    loginJoin: "Rejoignez le monde de la robotique! 🚀",
    loginTab: "Connexion",
    signupTab: "Nouveau Compte",
    nameLabel: "Votre Prénom",
    namePlaceholder: "ex. Ahmed le Héros",
    emailLabel: "Adresse Email",
    passLabel: "Mot de Passe",
    passPlaceholder6: "Au moins 6 caractères",
    loginBtn: "Commencer l'Aventure!",
    signupBtn: "Créer Mon Compte!",
    checking: "Vérification...",
    noAccount: "Pas de compte?",
    hasAccount: "Déjà un compte?",
    signupFree: "S'inscrire gratuitement",
    doLogin: "Se connecter",
    demoHint: "Essayez: n'importe quel email + mot de passe (6 chars) pour inscription rapide",
    backHome: "Accueil",
    reload: "Recharger",
    openSep: "Ouvrir séparément",
    yourProgress: "Votre Progression",
    lessonsList: "Liste des Leçons",
    heroTasks: "Tâches Héros",
    acquiredSkills: "Compétences Acquises",
    launchSim: "Lancer le Simulateur",
    openNew: "Ouvrir dans Nouvelle Fenêtre (Plus rapide)",
    clickToLoad: "Cliquez sur le bouton ci-dessous pour charger le simulateur",
    loading: "Chargement de",
    loadHint: "Cela peut prendre un moment — chargé une seule fois",
    lessonsCount: "leçons",
    footer: "© 2025 Académie RoboTech — Éducation robotique pour la prochaine génération",
    langLabel: "Langue",
    dashboard: "Ma Progression",
  },
} as const;

export type T = typeof translations.ar;

export function useLang() {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem(KEY) as Lang) ?? "ar";
  });

  useEffect(() => {
    localStorage.setItem(KEY, lang);
    const t = translations[lang];
    document.documentElement.setAttribute("dir", t.dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang]);

  const t: T = translations[lang];

  return { lang, setLang, t };
}
